/* Generated by scripts/gen-music-elevenlabs.mjs from assets/music/genres.json. Do not edit. */

/** A genre appears here once both of its tracks have been generated. */
export const MUSIC_GENRES: { id: string; name: string }[] = [
];

/** genre → the HARD track and the EASY track. */
export const MUSIC_TRACKS: Record<string, { high: number; low: number }> = {
};
