/**
 * Coach voices. Every voice records the same clip keys, so cue timing never
 * depends on who is speaking. Spoken only; never render these strings.
 * Clips are generated by scripts/gen-voice.py from this table's twin there.
 */
import type { CoachVoice } from '../types';

export type Clip =
  | 'welcome'
  | 'go'
  | 'hard0'
  | 'hard1'
  | 'hard2'
  | 'hard3'
  | 'hard4'
  | 'halfway'
  | 'three'
  | 'last'
  | 'easy0'
  | 'easy1'
  | 'easy2'
  | 'round0'
  | 'finish0'
  | 'count3'
  | 'count2'
  | 'count1'
  | 'preview';

export type RecordedVoice = Exclude<CoachVoice, 'off'>;

export const VOICE_LINES: Record<RecordedVoice, Partial<Record<Clip, string>>> = {
  /** Default. Up, bright, on your side. */
  direct: {
    welcome: "Let's ride! Easy spin to warm up.",
    go: 'Go!',
    hard0: 'Drive it!',
    hard1: 'Strong legs! Stay on it!',
    hard2: 'Quick feet! Keep it smooth!',
    hard3: "That's it! Hold the power!",
    hard4: 'Push! You own this!',
    halfway: 'Halfway! Looking strong!',
    three: 'Three to go! Dig in!',
    last: 'Last one! Everything you have!',
    easy0: 'Breathe. Nice work.',
    easy1: 'Spin it out.',
    easy2: 'Good! Recover.',
    round0: 'Set done! Spin easy and drink.',
    finish0: 'That is how it is done! Cool down, easy spin.',
    count3: 'Three!',
    count2: 'Two!',
    count1: 'One!',
    preview: 'Halfway! Looking strong!',
  },
  calm: {
    welcome: 'Warm-up. Easy spin to start.',
    go: 'Go.',
    hard0: 'Hold it.',
    hard1: 'Smooth and strong.',
    hard2: 'Quick feet.',
    hard3: 'Relax your shoulders.',
    hard4: 'Stay on it.',
    halfway: 'Halfway.',
    three: 'Three to go.',
    last: 'Last one. Empty it.',
    easy0: 'Breathe.',
    easy1: 'Spin easy.',
    easy2: 'Good.',
    round0: 'Set done. Spin easy, and drink.',
    finish0: "That's the work. Cool down, easy spin.",
    count3: 'Three.',
    count2: 'Two.',
    count1: 'One.',
    preview: 'Halfway. Smooth and strong.',
  },
  /** Numbers only: rep counts on HARD, silence on EASY. */
  numbers: {
    welcome: 'Warm-up.',
    go: 'Go.',
    halfway: 'Halfway.',
    three: 'Three to go.',
    last: 'Last one.',
    round0: 'Set done.',
    finish0: 'Done.',
    count3: 'Three.',
    count2: 'Two.',
    count1: 'One.',
    preview: 'Rep seven. Halfway.',
  },
};

export const MAX_REP_CLIP = 20;

export function repLine(rep: number): string {
  const words = [
    'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty',
  ];
  return `Rep ${words[rep] ?? rep}.`;
}

export function voiceName(voice: CoachVoice): string {
  switch (voice) {
    case 'calm':
      return 'Calm';
    case 'direct':
      return 'Coach';
    case 'numbers':
      return 'Numbers';
    default:
      return 'Off';
  }
}

/**
 * Which recorded clip and fallback text a cue plays in a voice, or null for
 * silence. The numbers voice turns plain HARD lines into the rep count and
 * keeps EASY quiet.
 */
export function resolveClip(
  voice: RecordedVoice,
  cue: { key: string; clip?: string; line: string; rep?: number },
): { clip: string; line: string } | null {
  const table = VOICE_LINES[voice];
  const clip = (cue.clip ?? '') as Clip;
  if (voice === 'numbers') {
    if (cue.key.startsWith('easy:')) return null;
    if (cue.key.startsWith('hard:') && !table[clip]) {
      if (cue.rep == null || cue.rep < 1 || cue.rep > MAX_REP_CLIP) return null;
      return { clip: `rep${cue.rep}`, line: repLine(cue.rep) };
    }
  }
  const line = table[clip];
  if (!line) return cue.line.trim() ? { clip: '', line: cue.line } : null;
  return { clip, line };
}
