#!/usr/bin/env python3
"""Render the coach voices from src/audio/voices.ts with Kokoro (local, offline).

  pip install kokoro-onnx soundfile numpy
  # model files: https://github.com/thewh1teagle/kokoro-onnx/releases (model-files-v1.0)
  python3 scripts/gen-voice.py --model kokoro-v1.0.onnx --voices voices-v1.0.bin

Writes assets/voice/<voice>/<clip>.mp3 (mono, 24 kHz, 64 kbps) and
src/audio/voiceClips.ts, the static require map the app bundles.
Every clip is trimmed, high-passed, gently compressed and matched to the same
loudness so no line jumps out over the music.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SR = 24000

# Kokoro speaker and pace per coach voice. af_heart is Kokoro's best-rated voice.
SPEAKERS = {
    "direct": ("af_bella", 1.06),  # the Coach: bright and energetic
    "calm": ("af_heart", 0.94),
    "numbers": ("af_heart", 0.98),
}
# Human takes win. Drop a recording at assets/voice-src/<voice>/<clip>.wav (any rate,
# mono or stereo) and this script uses it instead of the model. See docs/ux/voice-script.md.
SRC = ROOT / "assets/voice-src"
MAX_REP = 20
WORDS = [
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
]


def parse_table() -> dict[str, dict[str, str]]:
    src = (ROOT / "src/audio/voices.ts").read_text()
    body = src[src.index("VOICE_LINES"):src.index("export const MAX_REP_CLIP")]
    table: dict[str, dict[str, str]] = {}
    current = None
    for line in body.splitlines():
        m = re.match(r"\s{2}(\w+): \{", line)
        if m:
            current = m.group(1)
            table[current] = {}
            continue
        m = re.match(r"\s{4}(\w+): (['\"])(.*)\2,", line)
        if m and current:
            table[current][m.group(1)] = m.group(3).replace("\\'", "'")
    return table


def highpass(x: np.ndarray, cutoff: float) -> np.ndarray:
    a = float(np.exp(-2 * np.pi * cutoff / SR))
    y = np.empty_like(x)
    acc = 0.0
    for i, s in enumerate(x):
        acc += (1 - a) * (float(s) - acc)
        y[i] = s - acc
    return y


def polish(x: np.ndarray) -> np.ndarray:
    x = x.astype(np.float64)
    nz = np.where(np.abs(x) > 0.01)[0]
    if len(nz):
        x = x[max(0, nz[0] - int(0.012 * SR)): min(len(x), nz[-1] + int(0.06 * SR))]
    x = highpass(x, 90.0)
    # gentle soft-knee compression so short words carry over music
    rms = np.sqrt(np.mean(x ** 2)) or 1e-6
    x = x / rms * 0.12
    x = np.tanh(x * 1.6) / 1.6
    fade_in, fade_out = int(0.005 * SR), int(0.03 * SR)
    x[:fade_in] *= np.linspace(0, 1, fade_in)
    x[-fade_out:] *= np.linspace(1, 0, fade_out)
    peak = float(np.max(np.abs(x))) or 1.0
    return x * (0.89 / peak)


def write_mp3(path: Path, x: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", "pipe:0",
         "-codec:a", "libmp3lame", "-b:a", "64k", str(path)],
        input=x.astype(np.float32).tobytes(),
        check=True,
    )


def load_any(path: Path) -> np.ndarray:
    """Decode any audio file to mono float at SR through ffmpeg."""
    out = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-f", "f32le", "-ac", "1", "-ar", str(SR), "pipe:1"],
        capture_output=True,
        check=True,
    ).stdout
    return np.frombuffer(out, dtype=np.float32).copy()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--voices", required=True)
    args = ap.parse_args()
    from kokoro_onnx import Kokoro

    kokoro = Kokoro(args.model, args.voices)
    table = parse_table()
    requires: dict[str, dict[str, str]] = {}
    for voice, lines in table.items():
        speaker, speed = SPEAKERS[voice]
        jobs = dict(lines)
        if voice == "numbers":
            for n in range(1, MAX_REP + 1):
                jobs[f"rep{n}"] = f"Rep {WORDS[n]}."
        requires[voice] = {}
        for clip, text in jobs.items():
            human = SRC / voice / f"{clip}.wav"
            if human.exists():
                audio = load_any(human)
            else:
                audio, sr = kokoro.create(text, voice=speaker, speed=speed, lang="en-us")
                assert sr == SR, sr
            out = ROOT / "assets/voice" / voice / f"{clip}.mp3"
            write_mp3(out, polish(np.asarray(audio)))
            requires[voice][clip] = f"../../assets/voice/{voice}/{clip}.mp3"
            print(voice, clip, text)

    lines = [
        "/* Generated by scripts/gen-voice.py. Do not edit. */",
        "",
        "export const VOICE_CLIPS = {",
    ]
    for voice, clips in requires.items():
        lines.append(f"  {voice}: {{")
        for clip, rel in clips.items():
            lines.append(f"    {clip}: require('{rel}'),")
        lines.append("  },")
    lines.append("} as const;")
    lines.append("")
    (ROOT / "src/audio/voiceClips.ts").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
